name: Deploy Nuxt to Alwaysdata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Se placer à la racine
            cd $HOME
            
            # Nettoyage de sécurité si le dossier est corrompu
            if [ ! -d "www/.git" ]; then
              rm -rf www
              mkdir -p www
              cd www
              git clone https://github.com/yeadonaye/portfolio.git .
            else
              cd www
              git config --global --add safe.directory $(pwd)
              git fetch origin main
              git reset --hard origin/main
            fi

            # Environnement et Build
            export PATH=$PATH:/usr/local/bin
            npm install
            npm run build

            # Redémarrage forcé
            /usr/bin/alv-restart-site || alv-restart-site
